---
- hosts: all
  vars:
    - http_proxy: "{{ lookup('env','http_proxy') }}"
    # Docker tools versions
    - docker_compose_version: 1.4.2
    - rocker_version: 0.2.2
    - rocker_compose_version: 0.1.1
    # Default values
    - use_proxy: no
    - tmp_dir: /tmp
    - opt_dir: /opt
    - ansible_cache_dir: "{{tmp_dir}}/ansible"
    - software_install_dir: "{{ tmp_dir }}"
    - user_binaries: "{{ opt_dir }}"
  #vars_files:
    #- vars/dependencies.yml
  roles:
    #- setup
    - base
    - role: libevent
    - role: boost
    - role: thrift
    - role: snappy
    - role: gflags
    - role: glog
    - role: protobuf
    - role: gperftools
    - role: re2
    - role: liblfds
    - role: gtest
