---

- name: Install dependencies
  apt: name={{ item }} state=installed update_cache=yes
  sudo: yes
  with_items:
    - build-essential
    - python-dev
    - libbz2-dev
  when: ansible_os_family == "Debian"

- name: Install dependencies
  yum: name={{ item }} state=latest
  sudo: yes
  with_items:
    - python-devel
    - gcc
    - gcc-c++
    - kernel-devel
    - bzip2-devel
  when: ansible_os_family == "RedHat"

- name: Create work directory
  file: path={{ boost_work_dir }} state=directory

- name: Create install directory
  sudo: yes
  file: path={{ boost_prefix }} state=directory
  when: boost_prefix is defined

- name: Get boost source
  get_url:
   url: "{{ boost_tarball_url }}"
   dest: "{{ boost_work_dir }}"

- name: Unpack tarball
  command: /bin/tar jxfv {{ boost_work_dir }}/{{ boost_tarball_name }} -C {{ boost_work_dir }}
  no_log: False

- name: Bootstrap Boost
  command: chdir={{ boost_work_dir }}/{{ boost_build_dir }} ./bootstrap.sh
  when: boost_prefix is not defined

- name: Bootstrap Boost
  command: chdir={{ boost_work_dir }}/{{ boost_build_dir }} ./bootstrap.sh --prefix={{ boost_prefix }}
  when: boost_prefix is defined

- name: Make Boost
  command: chdir={{ boost_work_dir }}/{{ boost_build_dir }} ./b2

- name: Insall Boost
  sudo: yes
  command: chdir={{ boost_work_dir }}/{{ boost_build_dir }} ./b2 install
