- name: Download libevent
  get_url:
   url: "{{ libevent_tarball_url }}"
   dest: "{{tmp_dir}}/{{ libevent_tarball_name }}"
   mode: 0440

- name: Creates libevent directory
  file:
   path: "{{ libevent_work_dir }}"
   state: directory
   mode: 0775
   recurse: yes

- name: Unpack libevent
  unarchive:
    src: "{{ tmp_dir }}/{{ libevent_tarball_name }}"
    dest: "{{ libevent_work_dir }}"
    copy: no

- name: Configure libevent
  command: "chdir={{ libevent_work_dir }}/{{ libevent_version }} ./configure --prefix={{ libevent_prefix }}"
  register: "libevent_config"
- debug: "var=libevent_config"

- name: Make libevent
  command: "chdir={{ libevent_work_dir }}/{{ libevent_version }} make"

- name: Make install libevent
  command: "chdir={{ libevent_work_dir }}/{{ libevent_version }} make install"
