---

- name: Install | Ensure Thrift source downloaded
  git: repo={{ thrift_download_location }} dest={{ ansible_cache_dir }}/thrift-{{ thrift_version }} version={{ thrift_version }}
  register: 'thrift_download'
  sudo: yes

- name: Install | Ensure Thrift configured
  shell: chdir={{ansible_cache_dir}}/thrift-{{thrift_version}} ./bootstrap.sh
  sudo: yes
  when: 'thrift_download.changed'
  register: 'thrift'

- name: Install | Ensure Thrift configured
  shell: chdir={{ansible_cache_dir}}/thrift-{{thrift_version}} ./configure --with-lua=no
  sudo: yes
  when: 'thrift_download.changed'
  register: 'thrift'

- debug: "var=thrift"

- name: Install | Ensure Thrift make'd
  shell: chdir={{ansible_cache_dir}}/thrift-{{thrift_version}} make
  #environment:
  #      CPLUS_INCLUDE_PATH: /opt/libevent/include:/opt/libevent/include/event2
  sudo: yes
  when: 'thrift_download.changed'

- name: Install | Ensure Thrift installed
  shell: chdir={{ansible_cache_dir}}/thrift-{{thrift_version}} make install creates={{user_binaries}}/thrift
  sudo: yes
  when: 'thrift_download.changed'
