---

- name: Download re2
  get_url:
   url: "{{ re2_tarball_url }}"
   dest: "{{tmp_dir}}/{{ re2_tarball_name }}"
   mode: 0440

- name: Creates re2 directory
  file:
   path: "{{ re2_work_dir }}"
   state: directory
   mode: 0775
   owner: "vagrant"
   group: "vagrant"
   recurse: yes

- name: Unpack re2
  unarchive:
    src: "{{ tmp_dir }}/{{ re2_tarball_name }}"
    dest: "{{ re2_work_dir }}"
    copy: no

- name: Make re2
  command: "chdir={{ re2_work_dir }}/{{ re2_build_dir }} make"

- name: Make Test re2
  command: "chdir={{ re2_work_dir }}/{{ re2_build_dir }} make test"

- name: Make install re2
  command: "chdir={{ re2_work_dir }}/{{ re2_build_dir }} make install"
